version: 0.3
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@latest
  build:
    commands:
      - echo "Building Angular Project..." 
      - ng build --aot
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist/my-aws-project/ s3://www.estelinasbuffet.com-bucket --delete
